/**
 * Terms of Use and Privacy Policy, from the owner's document "وصول — شروط
 * الاستخدام وسياسة الخصوصية", adjusted to how Wsool actually works (Netlify
 * hosting, email code sign-in without passwords, no stored IP addresses).
 * {entity}, {registration}, {email}, {gateway}, {mailer}, {servers} are filled
 * from LEGAL in src/config/site.ts. Should be reviewed by a Saudi lawyer.
 */
export type Block = { h: string } | { p: string } | { ul: string[] } | { table: string[][] };
export type LegalDoc = { title: string; intro: string; blocks: Block[] };
export type LegalKind = "terms" | "privacy";

export const LEGAL_TEXT: Record<"ar" | "en", Record<LegalKind, LegalDoc>> = {
  ar: {
    terms: {
      title: "شروط الاستخدام",
      intro: "مرحباً بك في وصول. باستخدامك موقع wsool.link أو إنشاء حساب فيه، فأنت توافق على هذه الشروط. إذا لم توافق عليها، فلا تستخدم المنصة.",
      blocks: [
        { h: "1. من نحن" },
        { p: "وصول منصة تتيح لصناع المحتوى إنشاء صفحة تعريفية (ميديا كت) برابط خاص، يعرضون فيها معلوماتهم وأعمالهم للعلامات التجارية والوكالات. تديرها {entity}، {registration}، في المملكة العربية السعودية." },
        { h: "2. الأهلية والحساب" },
        { ul: [
          "يجب أن يكون عمرك 18 سنة أو أكثر لإنشاء حساب.",
          "تلتزم بتقديم معلومات صحيحة وتحديثها عند تغيّرها.",
          "أنت مسؤول عن حماية بريدك الإلكتروني الذي تدخل به، وعن كل ما يتم من خلال حسابك.",
          "الرابط الخاص (اسم المستخدم) يُمنح حسب التوفر، ولنا استرجاعه إذا كان مضللاً أو ينتحل اسم شخص أو علامة تجارية.",
        ] },
        { h: "3. المحتوى الذي تنشره" },
        { ul: [
          "أنت المالك لمحتواك من نصوص وصور وأرقام وروابط، وأنت المسؤول الوحيد عن صحته.",
          "تمنحنا ترخيصاً غير حصري ومجانياً لعرض محتواك واستضافته ونسخه بالقدر اللازم لتشغيل صفحتك وتصديرها، وينتهي هذا الترخيص بحذف المحتوى أو الحساب.",
          "معلومات التواصل التي تضيفها (رقم واتساب والبريد الإلكتروني) تُعرض للعامة على صفحتك بقرارك، وأنت تتحمّل مسؤولية نشرها.",
          "تقر بأن أرقام المتابعين والإحصائيات التي تعرضها صحيحة وغير مضللة.",
          "إذا أضفت رقم ترخيص (مثل رخصة موثوق)، فأنت تقر بأنه صحيح وساري.",
        ] },
        { h: "4. الاستخدام الممنوع" },
        { p: "يُمنع استخدام وصول في:" },
        { ul: [
          "انتحال شخصية أو علامة تجارية، أو نشر بيانات أو أرقام مزيفة.",
          "نشر محتوى مخالف للأنظمة في المملكة العربية السعودية أو مسيء أو ينتهك حقوق الغير.",
          "إرسال رسائل مزعجة أو جمع بيانات المستخدمين الآخرين آلياً.",
          "محاولة اختراق المنصة أو تعطيلها أو تجاوز قيود الباقات.",
        ] },
        { h: "5. الباقات والتجربة المجانية والدفع" },
        { ul: [
          "تتوفر باقة مجانية بمزايا محدودة، وباقة مدفوعة بمزايا متقدمة.",
          "عند التسجيل تحصل تلقائياً على تجربة مجانية لمدة 14 يوماً لكل مزايا الباقة المدفوعة، دون الحاجة لبطاقة دفع. عند انتهائها يتحوّل حسابك للباقة المجانية ما لم تشترك.",
          "سعر الباقة المدفوعة 49 ريالاً شهرياً أو 490 ريالاً سنوياً. الأسعار في الموقع الإنجليزي بالدولار الأمريكي.",
          "الأسعار تشمل ضريبة القيمة المضافة حيث تنطبق.",
          "يتجدد الاشتراك تلقائياً بنهاية كل فترة حتى تلغيه من لوحة التحكم.",
          "تتم المدفوعات عبر {gateway}، ولا نحتفظ ببيانات بطاقتك.",
          "قد نغيّر الأسعار مستقبلاً، وسنبلغك قبل التجديد التالي بمدة كافية.",
        ] },
        { h: "6. الإلغاء والاسترجاع" },
        { ul: [
          "يمكنك إلغاء الاشتراك في أي وقت، ويستمر وصولك للمزايا المدفوعة حتى نهاية الفترة المدفوعة.",
          "لا نسترجع المبالغ عن الفترة الجارية أو الأجزاء غير المستخدمة منها، إلا إذا ألزمتنا الأنظمة بذلك أو حدث خطأ في الخصم.",
          "عند انتهاء الاشتراك تبقى صفحتك على الباقة المجانية، وقد تتوقف المزايا المدفوعة مثل بعض القوالب وتصدير الميديا كت PDF.",
        ] },
        { h: "7. ملكيتنا الفكرية" },
        { p: "اسم وصول وشعاره وتصميم المنصة والقوالب والبرمجيات مملوكة لنا. لا يجوز نسخها أو إعادة استخدامها خارج استخدامك العادي للمنصة." },
        { h: "8. إيقاف الحساب وحذفه" },
        { ul: [
          "يمكنك حذف حسابك في أي وقت من صفحة الاشتراك في لوحة التحكم أو بمراسلتنا، مع مهلة 30 يوماً للتراجع.",
          "يحق لنا تعليق أي حساب أو حذفه أو إخفاء صفحته عند مخالفة هذه الشروط، مع إشعارك متى أمكن.",
        ] },
        { h: "9. إخلاء المسؤولية" },
        { ul: [
          "نقدّم المنصة «كما هي»، ونسعى لتشغيلها دون انقطاع، لكن لا نضمن خلوها التام من الأعطال.",
          "وصول ليس طرفاً في أي اتفاق أو تعاون يتم بينك وبين أي علامة تجارية أو وكالة، ولا يتحمّل مسؤولية التواصل أو الدفع أو التنفيذ بينكما.",
          "لا نضمن حصولك على تعاونات أو عملاء عبر صفحتك.",
        ] },
        { h: "10. حدود المسؤولية" },
        { p: "في حدود ما تسمح به الأنظمة، لا نتحمل أي أضرار غير مباشرة. ولا تتجاوز مسؤوليتنا الإجمالية تجاهك ما دفعته لنا خلال الأشهر الـ 12 السابقة للمطالبة." },
        { h: "11. تعديل الشروط" },
        { p: "قد نحدّث هذه الشروط من وقت لآخر. عند وجود تغيير جوهري سنبلغك بالبريد أو عبر لوحة التحكم، واستمرارك في الاستخدام بعد السريان يعني موافقتك." },
        { h: "12. النظام الحاكم" },
        { p: "تخضع هذه الشروط لأنظمة المملكة العربية السعودية، وتختص المحاكم في مدينة الرياض بالنظر في أي نزاع. وعند الاختلاف بين النسختين العربية والإنجليزية، تُعتمد النسخة العربية." },
        { h: "13. التواصل" },
        { p: "لأي سؤال عن هذه الشروط: {email}" },
      ],
    },
    privacy: {
      title: "سياسة الخصوصية",
      intro: "توضح هذه السياسة كيف تجمع وصول بياناتك الشخصية وتستخدمها وتحميها، وفقاً لنظام حماية البيانات الشخصية في المملكة العربية السعودية. الجهة المسؤولة عن بياناتك: {entity}، {registration}.",
      blocks: [
        { h: "1. البيانات التي نجمعها" },
        { table: [
          ["النوع", "أمثلة", "مصدرها"],
          ["بيانات الحساب", "البريد الإلكتروني (ندخلك برمز يوصلك عليه، بدون كلمة مرور)", "أنت عند التسجيل"],
          ["محتوى صفحتك", "الاسم، النبذة، الصور، روابط الحسابات، أرقام المتابعين، الأعمال، رقم الترخيص", "أنت من لوحة التحكم"],
          ["لقطات التوثيق", "صور شاشة حساباتك لإثبات الأرقام، تُحفظ بشكل خاص ويراها فريق المراجعة فقط", "أنت عند طلب التوثيق"],
          ["بيانات التواصل المعروضة", "رقم واتساب، البريد الإلكتروني", "أنت، وتُعرض للعامة بقرارك"],
          ["بيانات الاشتراك", "نوع الباقة، تواريخ الدفع، الفواتير", "{gateway}"],
          ["بيانات الزوار", "عدد الزيارات والنقرات ودولة الزائر. لا نحفظ عنوان IP", "تلقائياً عند زيارة صفحتك"],
          ["بيانات تقنية", "لغة الجهاز، وملفات تعريف ضرورية لتسجيل الدخول وحفظ اللغة", "تلقائياً"],
        ] },
        { p: "لا نجمع بيانات بطاقتك كاملة، ولا نبيع بياناتك لأي جهة." },
        { h: "2. لماذا نستخدمها" },
        { ul: [
          "لتشغيل حسابك وعرض صفحتك وتصدير الميديا كت.",
          "لإدارة التجربة المجانية والاشتراك والفواتير.",
          "لإظهار إحصائيات صفحتك (عدد الزيارات والدول فقط).",
          "لعرض الصفحة بلغة جهاز الزائر.",
          "لإرسال رسائل ضرورية مثل انتهاء التجربة والتجديد وتغيير الشروط.",
          "لإرسال النشرة البريدية فقط إن اشتركت فيها وأكّدت اشتراكك، ويمكنك إلغاؤها في أي وقت.",
          "لحماية المنصة ومنع الاحتيال والالتزام بالأنظمة.",
        ] },
        { h: "3. الأساس النظامي" },
        { p: "نعالج بياناتك بناءً على: تنفيذ الخدمة التي طلبتها، وموافقتك (مثل النشرة البريدية)، ومصلحتنا المشروعة في حماية المنصة وتحسينها، والالتزامات النظامية مثل الفوترة والضريبة." },
        { h: "4. مع من نشاركها" },
        { p: "نشاركها فقط مع مزودي خدمة يساعدوننا في تشغيل المنصة، وبالقدر اللازم:" },
        { ul: [
          "Supabase: قاعدة البيانات وتسجيل الدخول وتخزين الملفات.",
          "Netlify و Cloudflare: استضافة الموقع وتوصيله.",
          "{gateway}: معالجة المدفوعات.",
          "{mailer}: إرسال الرسائل.",
        ] },
        { p: "وقد نفصح عنها للجهات الحكومية المختصة إذا طُلب ذلك نظاماً." },
        { h: "5. نقل البيانات خارج المملكة" },
        { p: "تُخزّن بياناتك على خوادم مزودينا في {servers}. نحرص أن يتم ذلك وفق ضوابط نقل البيانات المعتمدة في المملكة، وبضمانات حماية مناسبة." },
        { h: "6. مدة الاحتفاظ" },
        { ul: [
          "نحتفظ ببيانات حسابك وصفحتك طوال فترة وجود الحساب.",
          "عند حذف الحساب نحذف بياناتك خلال 30 يوماً، عدا ما يلزمنا النظام بالاحتفاظ به مثل سجلات الفواتير.",
          "إحصائيات الزوار تُحفظ بشكل لا يحدد هوية الأشخاص.",
        ] },
        { h: "7. حقوقك" },
        { p: "يحق لك:" },
        { ul: [
          "معرفة البيانات التي نحتفظ بها عنك والحصول على نسخة منها، وتقدر تحمّلها بنفسك من صفحة الاشتراك.",
          "تصحيح بياناتك أو تحديثها، ومعظمها متاح مباشرة من لوحة التحكم.",
          "طلب حذف بياناتك أو حسابك.",
          "سحب موافقتك على النشرة البريدية في أي وقت.",
          "تقديم شكوى إلى الجهة المختصة بحماية البيانات في المملكة.",
        ] },
        { p: "لممارسة أي حق راسلنا على {email}، وسنرد خلال 30 يوماً." },
        { h: "8. ملفات تعريف الارتباط" },
        { p: "نستخدم ملفات ضرورية فقط لتسجيل الدخول وحفظ اللغة. لا نستخدم ملفات إعلانية أو تتبع من طرف ثالث." },
        { h: "9. حماية البيانات" },
        { p: "نستخدم التشفير أثناء النقل، والدخول برموز لمرة واحدة بدل كلمات المرور، وصلاحيات وصول محدودة لفريقنا حسب الحاجة مع سجل لكل إجراء. ومع ذلك لا توجد وسيلة حماية كاملة 100%." },
        { h: "10. الأطفال" },
        { p: "المنصة غير موجهة لمن هم دون 18 سنة، ولا نجمع بياناتهم عن علم." },
        { h: "11. تحديث السياسة" },
        { p: "قد نحدّث هذه السياسة، وسنبلغك بأي تغيير جوهري بالبريد أو عبر لوحة التحكم." },
        { h: "12. التواصل" },
        { p: "للاستفسارات وطلبات الخصوصية: {email}" },
      ],
    },
  },
  en: {
    terms: {
      title: "Terms of Use",
      intro: "Welcome to Wsool. By using wsool.link or creating an account, you agree to these Terms. If you do not agree, please do not use the platform.",
      blocks: [
        { h: "1. Who we are" },
        { p: "Wsool lets content creators build a media kit page with a personal link, showing their profile and work to brands and agencies. It is operated by {entity}, {registration}, Kingdom of Saudi Arabia." },
        { h: "2. Eligibility and accounts" },
        { ul: [
          "You must be at least 18 years old to create an account.",
          "You agree to provide accurate information and keep it up to date.",
          "You are responsible for securing the email address you sign in with and for all activity under your account.",
          "Usernames are assigned on availability. We may reclaim a username that is misleading or impersonates a person or brand.",
        ] },
        { h: "3. Your content" },
        { ul: [
          "You own your content (text, images, numbers, links) and are solely responsible for its accuracy.",
          "You grant us a non-exclusive, royalty-free licence to host, display and copy your content as needed to run and export your page. This licence ends when you delete the content or your account.",
          "Contact details you add (WhatsApp number, email) are shown publicly on your page by your choice, and you are responsible for publishing them.",
          "You confirm that follower counts and statistics you display are accurate and not misleading.",
          "If you add a licence number (such as a Mawthooq licence), you confirm it is valid and current.",
        ] },
        { h: "4. Prohibited use" },
        { p: "You may not use Wsool to:" },
        { ul: [
          "Impersonate any person or brand, or publish fake data or numbers.",
          "Publish content that is unlawful, offensive or infringes others' rights.",
          "Send spam or scrape other users' data.",
          "Attempt to hack, disrupt or bypass plan limits on the platform.",
        ] },
        { h: "5. Plans, free trial and payment" },
        { ul: [
          "We offer a Free plan with limited features and a paid plan with advanced features.",
          "On signup you automatically get a 14-day free trial of all paid features. No card is required. When it ends, your account moves to the Free plan unless you subscribe.",
          "The paid plan costs USD 13 per month or USD 130 per year on the English site (SAR 49 / 490 on the Arabic site).",
          "Prices include VAT where applicable.",
          "Subscriptions renew automatically at the end of each period until you cancel from your dashboard.",
          "Payments are processed by {gateway}. We do not store your card details.",
          "We may change prices and will notify you in good time before your next renewal.",
        ] },
        { h: "6. Cancellation and refunds" },
        { ul: [
          "You can cancel anytime. You keep paid features until the end of your current billing period.",
          "We do not refund the current period or unused portions of it, unless required by law or in case of a billing error.",
          "When a subscription ends, your page stays on the Free plan and paid features (such as some templates and PDF media kit export) may stop.",
        ] },
        { h: "7. Our intellectual property" },
        { p: "The Wsool name, logo, design, templates and software belong to us. You may not copy or reuse them outside normal use of the platform." },
        { h: "8. Suspension and deletion" },
        { ul: [
          "You can delete your account anytime from the Subscription page in your dashboard or by contacting us, with a 30-day window to undo.",
          "We may suspend or remove an account or hide a page that breaches these Terms, and will notify you where possible.",
        ] },
        { h: "9. Disclaimers" },
        { ul: [
          "The platform is provided \"as is\". We aim for uninterrupted service but cannot guarantee it is error-free.",
          "Wsool is not a party to any agreement between you and a brand or agency, and is not responsible for communication, payment or delivery between you.",
          "We do not guarantee that you will get collaborations or clients through your page.",
        ] },
        { h: "10. Limitation of liability" },
        { p: "To the extent permitted by law, we are not liable for indirect damages. Our total liability to you will not exceed the amount you paid us in the 12 months before the claim." },
        { h: "11. Changes to these Terms" },
        { p: "We may update these Terms. For material changes we will notify you by email or in your dashboard. Continuing to use Wsool after the effective date means you accept them." },
        { h: "12. Governing law" },
        { p: "These Terms are governed by the laws of the Kingdom of Saudi Arabia, and the courts of Riyadh have jurisdiction over any dispute. If the Arabic and English versions differ, the Arabic version prevails." },
        { h: "13. Contact" },
        { p: "Questions about these Terms: {email}" },
      ],
    },
    privacy: {
      title: "Privacy Policy",
      intro: "This policy explains how Wsool collects, uses and protects your personal data, in line with the Saudi Personal Data Protection Law. The controller of your data is {entity}, {registration}.",
      blocks: [
        { h: "1. Data we collect" },
        { table: [
          ["Type", "Examples", "Source"],
          ["Account data", "Email address (you sign in with a code we send there; no password)", "You, at signup"],
          ["Page content", "Name, bio, photos, social links, follower counts, work samples, licence number", "You, from the dashboard"],
          ["Verification screenshots", "Screenshots of your accounts proving your numbers, stored privately and seen only by our review team", "You, when requesting verification"],
          ["Public contact details", "WhatsApp number, email", "You; shown publicly by your choice"],
          ["Subscription data", "Plan, payment dates, invoices", "{gateway}"],
          ["Visitor data", "Visit and click counts and visitor country. We do not store IP addresses", "Automatic, when your page is viewed"],
          ["Technical data", "Device language, essential cookies for login and language", "Automatic"],
        ] },
        { p: "We never collect your full card details, and we do not sell your data." },
        { h: "2. How we use it" },
        { ul: [
          "To run your account, display your page and export your media kit.",
          "To manage your free trial, subscription and invoices.",
          "To show your page statistics (visit counts and countries only).",
          "To show pages in the visitor's device language.",
          "To send essential emails such as trial ending, renewals and changes to our terms.",
          "To send our newsletter only if you subscribe and confirm; you can unsubscribe anytime.",
          "To protect the platform, prevent fraud and comply with the law.",
        ] },
        { h: "3. Legal basis" },
        { p: "We process your data to deliver the service you requested, with your consent (e.g. newsletter), for our legitimate interest in securing and improving the platform, and to meet legal obligations such as billing and tax." },
        { h: "4. Who we share it with" },
        { p: "Only with service providers that help us run Wsool, and only as needed:" },
        { ul: [
          "Supabase: database, sign-in and file storage.",
          "Netlify and Cloudflare: website hosting and delivery.",
          "{gateway}: payment processing.",
          "{mailer}: sending emails.",
        ] },
        { p: "We may disclose data to competent authorities when legally required." },
        { h: "5. International transfers" },
        { p: "Your data is stored on our providers' servers in {servers}. We make sure such transfers follow the rules applicable in Saudi Arabia, with appropriate safeguards." },
        { h: "6. Retention" },
        { ul: [
          "We keep your account and page data for as long as your account exists.",
          "When you delete your account, we delete your data within 30 days, except records we must keep by law, such as invoices.",
          "Visitor statistics are kept in a form that does not identify individuals.",
        ] },
        { h: "7. Your rights" },
        { p: "You have the right to:" },
        { ul: [
          "Know what data we hold about you and get a copy; you can download it yourself from the Subscription page.",
          "Correct or update your data; most of it is editable in your dashboard.",
          "Request deletion of your data or account.",
          "Withdraw consent to the newsletter at any time.",
          "Lodge a complaint with the competent data protection authority in Saudi Arabia.",
        ] },
        { p: "To exercise any right, email {email}. We will reply within 30 days." },
        { h: "8. Cookies" },
        { p: "We use only essential cookies for login and language preference. We do not use advertising or third-party tracking cookies." },
        { h: "9. Security" },
        { p: "We use encryption in transit, one-time sign-in codes instead of passwords, and limited, need-based staff access with every action logged. No method of protection is 100% secure." },
        { h: "10. Children" },
        { p: "Wsool is not intended for anyone under 18, and we do not knowingly collect their data." },
        { h: "11. Changes to this policy" },
        { p: "We may update this policy and will notify you of material changes by email or in your dashboard." },
        { h: "12. Contact" },
        { p: "Privacy questions and requests: {email}" },
      ],
    },
  },
};
